apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-external-to-pod1
  namespace: external
spec:
  podSelector:
    matchLabels:
      app: pod1-webapp
  policyTypes:
  - Ingress
  ingress:
  - {}

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-pod1-to-pod2
  namespace: external
spec:
  podSelector:
    matchLabels:
      app: pod1-webapp
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: internal
      podSelector:
        matchLabels:
          app: pod2-ssh
    ports:
    - protocol: TCP
      port: 22

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-pod1-ingress-to-pod2
  namespace: internal
spec:
  podSelector:
    matchLabels:
      app: pod2-ssh
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: external
      podSelector:
        matchLabels:
          app: pod1-webapp
    ports:
    - protocol: TCP
      port: 22
