apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod1-webapp
  namespace: external
  labels:
    app: pod1-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod1-webapp
  template:
    metadata:
      labels:
        app: pod1-webapp
    spec:
      containers:
      - name: webapp
        image: vulnerable-webapp:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
          - name: MODE
            valueFrom:
              configMapKeyRef:
                name: pod1-config
                key: APP_MODE
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                name: pod1-secrets
                key: DATABASE_URL
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        # Add security context if needed for sudo NOPASSWD later
        # securityContext:
        #   capabilities:
        #     add: ["SYS_ADMIN"] # Example, adjust as needed for sudo setup
