apiVersion: v1
kind: Service
metadata:
  name: pod1-webapp-service
  namespace: external
spec:
  selector:
    app: pod1-webapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
