apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod2-ssh
  namespace: internal
  labels:
    app: pod2-ssh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod2-ssh
  template:
    metadata:
      labels:
        app: pod2-ssh
    spec:
      serviceAccountName: cluster-admin-sa 
      containers:
      - name: sshd
        image: ssh-server
        imagePullPolicy: Never
        ports:
        - containerPort: 22
        livenessProbe:
            tcpSocket:
              port: 22
            initialDelaySeconds: 15
            periodSeconds: 20
        readinessProbe:
            tcpSocket:
              port: 22
            initialDelaySeconds: 5
            periodSeconds: 10
        volumeMounts:
        - name: ssh-key-volume
          mountPath: /root/.ssh
          readOnly: true
        securityContext:
          privileged: true
      volumes:
      - name: ssh-key-volume
        secret:
          secretName: pod2-ssh-key
          items:
          - key: authorized_keys
            path: authorized_keys
      hostPID: true 
