apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-admin-sa
# Note: By default, this SA is created in the 'default' namespace unless specified otherwise.
# Ensure Pod 2 deployment references this SA in the correct namespace if not 'default'.

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-admin-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"] # Extremely permissive!

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-binding
subjects:
- kind: ServiceAccount
  name: cluster-admin-sa
  namespace: default # Make sure this matches the namespace where the SA is created/used
roleRef:
  kind: ClusterRole
  name: cluster-admin-role
  apiGroup: rbac.authorization.k8s.io
